__version__      = '0.1.0.dev1'
__author__       = 'John Thorvald Wodder II'
__author_email__ = 'statjson@varonathe.org'
__license__      = 'MIT'
__url__          = 'https://github.com/jwodder/statjson'
